INSERT INTO SCRIPT_SCHEMA.APPLICATIONS (APP_NAME, DESCRIPTION, OWNER)
    VALUES ('APP_NAME 1', 'APP DESCRIPTION 1', 'APP OWNER 1');

INSERT INTO SCRIPT_SCHEMA.RELEASES (RELEASE_DATE, DESCRIPTION)
    VALUES (CURRENT_TIMESTAMP, 'RELEASE DESCRIPTION');

INSERT INTO SCRIPT_SCHEMA.TICKETS (TITLE, STATUS, DESCRIPTION, APPLICATION_ID)
    VALUES ('TICKET TITLE 1', 'TICKET STATUS 1', 'TICKET DESCRIPTION 1', NULL);

INSERT INTO SCRIPT_SCHEMA.APPLICATIONS (APPLICATION_ID, APP_NAME, DESCRIPTION, OWNER)
    VALUES (0, 'APP_NAME 0', 'APP DESCRIPTION 0', 'APP OWNER 0');

INSERT INTO SCRIPT_SCHEMA.RELEASES (ID, RELEASE_DATE, DESCRIPTION)
    VALUES (0, CURRENT_TIMESTAMP, 'RELEASE DESCRIPTION');

INSERT INTO SCRIPT_SCHEMA.RELEASES_APPLICATION(RELEASE_ENTITY_ID, APPLICATIONS_APPLICATION_ID)
    VALUES (0, 0);

INSERT INTO SCRIPT_SCHEMA.TICKETS (ID, TITLE, STATUS, DESCRIPTION, APPLICATION_ID)
    VALUES (0, 'TICKET TITLE 1', 'TICKET STATUS 1', 'TICKET DESCRIPTION 1', 0);

INSERT INTO SCRIPT_SCHEMA.TICKET_RELEASE(RELEASE_FK, TICKET_FK)
    VALUES (0, 0);